### ISSUE TITLE
editor endless loop

### ISSUE THREAD

**Issue by lusons** [NWYLZW/shikitor#11]
### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

![695b19aa5db691c4bd1aca49acd8bbdc](https://github.com/NWYLZW/shikitor/assets/67620295/e3c0d2d4-8ca4-4a10-b1b1-e11ce0935c43)

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by NWYLZW** [comment]
Fix #12
