### ISSUE TITLE
Failing to delete selection

### ISSUE THREAD

**Issue by g-plane** [NWYLZW/shikitor#6]
### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Select some text as below:

![image](https://github.com/NWYLZW/shikitor/assets/17216317/8b5c71bf-f90d-4ff7-a8a9-08e222a27d0e)

Then, press <kbd>Backspace</kbd> or <kbd>Del</kbd> to delete such selection, but nothing changed.

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by NWYLZW** [comment]
I'm not sure if I fixed this issue, but it doesn't seem to be reproducible on my end. If you have more information, please provide feedback to me.

**Comment by g-plane** [comment]
It got fixed.
